sudo: false
language: node_js
matrix:
    fast_finish: true
    allow_failures:
        - node_js: "5"
node_js:
    - "0.10"
    - "0.12"
    - "4"
    - "5"
env:
    global:
        - NODE_ENV=test
        - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
